version: '2'
services:
  mongo:
    image: "mongo"
    container_name: mongo_container
    ports:
      - "27017:27017"

  flask:
    build:
      context: ./flask/
      dockerfile: Dockerfile
    image: flask_image
    container_name: flask_container
    ports:
      - "8000:8000"
    volumes:
      - "$PWD/flask:/home/flask"
    links: 
      - mongo
  soup:
    build:
      context: ./soup/
      dockerfile: Dockerfile
    image: soup_image
    container_name: soup_container
    volumes:
      - "$PWD/soup:/home/soup"
    links: 
      - mongo
